environments:
  dev:
    project_id: gcp-demos-411520
    dataset: bgg_data_dev
    bucket: bgg-data-warehouse-dev
    location: US
    
  test:
    project_id: gcp-demos-411520
    dataset: bgg_data_test
    bucket: bgg-data-warehouse-test
    location: US
    
  prod:
    project_id: gcp-demos-411520
    dataset: bgg_data_prod
    bucket: bgg-data-warehouse-prod
    location: US

datasets:
  raw: bgg_raw_test

tables:
  games:
    name: games
  
raw_tables:
  raw_responses:
    name: raw_responses
  thing_ids:
    name: thing_ids
  fetch_in_progress:
    name: fetch_in_progress
  request_log:
    name: request_log
